apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: pokedexcompositeworkloads.deployments.bluesolution.es
spec:
  compositeTypeRef:
    apiVersion: deployments.bluesolution.es/v1alpha1
    kind: PokedexCompositeWorkload
  mode: Pipeline
  pipeline:
    - step: normal
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        metadata:
          name: basic
        spec:
          config:
            debug: true
          dependencies: |
            k8s = "1.31.2"
            konfig = { path = "../../../konfig" }
            deployments = { path = "../../../deployments" }
          # source: github.com/Javier-Godon/cluster-continuous-delivery/apps/deployments/pokedex/dev
          params:
            providerConfigRef:
              name: kubernetes-provider
            annotations:
              config.kubernetes.io/local-config: "true"
