apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blue-services
  namespace: argocd
spec:
  description: Project for deploy infrastructure in kubernetes
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
