apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: reactive-pokedex-github-pipelinerun-
  namespace: tekton-workspace
spec:
  pipelineRef:
    name: git-clone-and-build-pipeline
  params:
    - name: gitUrl
      value: git@github.com:Javier-Godon/ddd-hexagonal-vertical-slice-cqrs-reactive-kubernetes.git
    - name: revision
      value: main
    - name: branch-name
      value: main
    - name: pathToContext
      value: pokedex
    - name: imageUrl
      value: ghcr.io/javier-godon/ddd-hexagonal-vertical-slice-cqrs-reactive-kubernetes
    - name: imageTag
      value: v0.0.1-SNAPSHOT
  serviceAccountName: github-clone-serviceaccount
  workspaces:
    - name: maven-settings
      configMap:
        name: tekton-maven-settings
    - name: dockerconfig
      secret:
        secretName: dockerconfig-gitlab-secret
      # secret:
      #   secretName: gitlab-registry-secret
    - name: git-source
      volumeClaimTemplate:
        metadata:
          name: reactive-pokedex-source-pvc
          namespace: tekton-workspace
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
      # - name: git-source
      #   persistentVolumeClaim:
      #     claimName: erp-catalog-source-pvc
