apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mongodbcompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: MongodbCompositeWorkload
    plural: mongodbcompositeworkloads
  claimNames:
    kind: MongodbWorkload
    plural: mongodbworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string