apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: nginxcompositeworkloads.gitops.bluesolution.es
spec:
  compositeTypeRef:
    apiVersion: gitops.bluesolution.es/v1alpha1
    kind: NginxCompositeWorkload
  resources:
    - name: nginxNamespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        metadata:
          name: nginx-namespace
          # namespace: default
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: nginx-ingress
          providerConfigRef:
            name: kubernetes-provider

    
    - name: nginxIngressBlue
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: kubernetes-provider
          forProvider:
            manifest: 
              apiVersion: charts.nginx.org/v1alpha1
              kind: NginxIngress
              metadata:
                name: blue-nginxingress
                namespace: nginx-ingress
              spec:
                controller:
                  image:
                    pullPolicy: IfNotPresent
                    repository: nginx/nginx-ingress
                    tag: 3.7.0-ubi
                  ingressClass:
                    name: nginx
                  kind: deployment
                  nginxplus: false
                  replicaCount: 1
                  serviceAccount:
                    imagePullSecretName: ""       