apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/dockerfile"
        - "--context=dir://workspace"
        - "--destination=<gcr.io/$PROJECT/$IMAGE:$TAG>" # replace with your account
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
        - name: dockerfile-storage
          mountPath: /workspace        
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: kaniko-pv-claim