apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: kafkacompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: KafkaCompositeWorkload
    plural: kafkacompositeworkloads
  claimNames:
    kind: KafkaWorkload
    plural: kafkaworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string