apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: tektoncompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: TektonCompositeWorkload
    plural: tektoncompositeworkloads
  claimNames:
    kind: TektonWorkload
    plural: tektonworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                label:
                  type: object
                  properties:
                    tektonNamespace:
                      type: string  
