apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: nexus-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/nexus-volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
spec:
  storageClassName: nexus-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi