apiVersion: v1
kind: PersistentVolume
metadata:
  name: blue-mongodb-pv
  labels:
    type: local
spec:
  storageClassName: blue-mongodb-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mongodb-volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-mongodb-pvc
spec:
  storageClassName: blue-mongodb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi