name: Generate YAML Manifests From Kcl Konfig

on:
  push:
    paths:
      - "**/*.k" # Trigger only when KCL files are changed
      - "**apps/deployments/**" # Trigger if deployments are updated and

jobs:
  generate-yaml:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full Git history

      # kcl: https://www.kcl-lang.io/docs/next/user_docs/guides/package-management/how-to/push_github_action
      # Step 2: Set up Go environment
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # Step 3: Install KCL CLI
      - name: Install KCL CLI
        run: go install kcl-lang.io/cli/cmd/kcl@latest

      # Step 4: Identify Changed Folders
      - name: Determine changed folders
        id: changes
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            BASE_REF="HEAD~1"
          else
            BASE_REF="${{ github.event.before }}"
          fi

          git fetch origin $BASE_REF

          # Detect changes in 'base' and specific environments
          BASE_CHANGED=$(git diff --name-only $BASE_REF ${{ github.sha }} | grep '^apps/deployments/.*/base/' || true)
          ENV_CHANGED=$(git diff --name-only $BASE_REF ${{ github.sha }} | grep '^apps/deployments/.*/\(dev\|stg\|pro\)/' || true)

          echo "Base changes detected in: $BASE_CHANGED"
          echo "Environment changes detected in: $ENV_CHANGED"

          # Create environment list for projects affected by 'base' changes
          AFFECTED_PROJECTS=$(echo "$BASE_CHANGED" | awk -F'/' '{print $3}' | sort -u)
          ENV_FOLDERS=$(echo "$ENV_CHANGED" | awk -F'/' '{print $3"/"$4}' | sort -u)

          echo "Affected projects from base: $AFFECTED_PROJECTS"
          echo "Affected environment folders: $ENV_FOLDERS"

          # Save results
          echo "projects=$AFFECTED_PROJECTS" >> $GITHUB_ENV
          echo "env_folders=$ENV_FOLDERS" >> $GITHUB_ENV

      # Debug changed projects and environments
      - name: Debug changed projects and environments
        run: |
          echo "Projects affected by base: ${{ env.projects }}"
          echo "Environment folders affected: ${{ env.env_folders }}"

      # Step 5: Generate manifests for affected folders
      - name: Generate manifests for base and environment changes
        run: |
          # Process base changes (generate manifests for all environments in the project)
          for PROJECT in ${{ env.projects }}; do
            echo "Processing all environments for project: $PROJECT"
            for ENV in dev stg pro; do
              OUTPUT_DIR="apps/deployments/$PROJECT/$ENV/manifests"
              mkdir -p $OUTPUT_DIR
              kcl -d apps/deployments/$PROJECT/base -o $OUTPUT_DIR/kubernetes-manifests.yaml
            done
          done

          # Process individual environment changes
          for FOLDER in ${{ env.env_folders }}; do
            PROJECT=$(echo $FOLDER | cut -d'/' -f1)
            ENVIRONMENT=$(echo $FOLDER | cut -d'/' -f2)
            echo "Processing specific environment: $PROJECT/$ENVIRONMENT"
            OUTPUT_DIR="apps/deployments/$PROJECT/$ENVIRONMENT/manifests"
            mkdir -p $OUTPUT_DIR
            kcl -d apps/deployments/$PROJECT/$ENVIRONMENT -o $OUTPUT_DIR/kubernetes-manifests.yaml
          done

      # Step 6: Commit and push changes
      - name: Commit and push manifests
        if: ${{ env.folders != '' }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add apps/deployments/*/*/manifests/
          git commit -m "Update manifests for changed environments"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
