name: Update image tag in pokedex dev

on:
  repository_dispatch:
    types:
      - image-tag-in-pokedex-dev-updated

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install kcl-lib
        run: pip install kcl-lib

      - name: Update image in KCL
        run: |
          python -c "
          import kcl_lib.api as api

          file = 'apps/deployments/pokedex/dev/main.k'
          specs = [f'pokedexApplication.image=\"ghcr.io/javier-godon/ddd-hexagonal-vertical-slice-cqrs-reactive-kubernetes:${{ github.event.client_payload.image_tag }}\"']
          args = api.OverrideFile_Args(file=file, specs=specs)
          api.API().override_file(args)
          "

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add apps/deployments/pokedex/dev/main.k
          git commit -m "Update image to ghcr.io/javier-godon/ddd-hexagonal-vertical-slice-cqrs-reactive-kubernetes:${{ github.event.client_payload.image_tag }}"
          git push

      - name: Generate YAML Manifests from KCL
        run: |
          python -c "
          import kcl_lib.api as api

          input_file = 'apps/deployments/pokedex/dev/main.k'
          output_file = 'apps/deployments/pokedex/dev/manifests/kubernetes-manifests.yaml'

          args = api.ExecProgram_Args(k_filename_list=[input_file])
          api = api.API()
          yaml_result = api.exec_program(args).yaml_result

          with open(output_file, 'w') as f:
              f.write(yaml_result)

          print(f'YAML manifests generated and saved to {output_file}')
          "
      - name: Commit and Push Changes for Manifests
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add apps/deployments/pokedex/dev/manifests/kubernetes-manifests.yaml
          git commit -m "Generate pokedex dev manifests for updated image tag: ${{ github.event.client_payload.image_tag }}"
          git push
